# Tcl package index file, version 1.0
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded tclx 0.1 [list tclPkgSetup $dir tclx 0.1 {{forfile.tcl source for_file} {stringfile.tcl source {read_file write_file}} {pushd.tcl source {dirs popd pushd}} {globrecur.tcl source {for_recursive_glob recursive_glob}} {tclx.tcl source {abs avg lassign lempty lvarcat lvarpop lvarpush max min}} {xtcl_keygetset.tcl source {keylget keylset}} {setfuncs.tcl source {intersect intersect3 lrmdups union}}}]
